workflows:
  main:
    name: Main Workflow
    environment:
      XCODE_SCHEME: "UniScore"
      XCODE_WORKSPACE: "UniScore.xcworkspace"
      XCODE_PROJECT: "UniScore.xcodeproj"
    scripts:
      - name: Install CocoaPods
        script: |
          #!/bin/bash

          if [ -f "ios/Podfile" ]; then
            echo "Podfile found, installing CocoaPods dependencies..."
            gem install cocoapods
            cd ios && pod install && cd ..
          else
            echo "Podfile not found, skipping CocoaPods installation."
          fi

      - name: Build and test
        script: |
          #!/bin/bash
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME clean build test
